//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace ServicioMusicaWCF
{
    using System;
    using System.Collections.Generic;
    
    public partial class DetallesConcierto
    {
        public int IdConcierto { get; set; }
        public int IdCancion { get; set; }
        public int Orden { get; set; }
    
        public virtual Canciones Canciones { get; set; }
        public virtual Conciertos Conciertos { get; set; }
    }
}
